Repository Growthers/Oshavery-Front, pull requests merged in 2021-09, with the labels that each got.

#81 update next.js
  package.json
  yarn.lock
Labels: bug

#78 MarkDownの表示テスト
  package.json
  src/components/molecules/ChannelMessage.tsx
  src/components/molecules/math.js
  src/components/organisms/ChannelMessages.tsx
  yarn.lock
Labels: WIP

#96 Feat/emoji picker
  package.json
  src/components/molecules/EmojiPicker.tsx
  yarn.lock
Labels: enhancement

#104 fix/ Windowsでyarn installができない不具合の解消
  package.json
Labels: bug

#131 feat/login
  package.json
  src/pages/_app.tsx
  src/pages/api/auth/[auth0].ts
  yarn.lock
Labels: Priority: high

#148 OGP画像の設定
  src/components/Layout.tsx
Labels: Geek

#149 Feat/login
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/index.tsx
  src/styles/components/Footer.module.scss
Labels: component

#180 fix emoji mart
  src/app_components/molecules/EmojiPicker.tsx
Labels: bug
